/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#42525a",
        "on-secondary-container": "#44545c",
        "secondary": "#4e5e66",
        "on-primary": "#ffeefd",
        "on-primary-fixed": "#110018",
        "on-primary-container": "#47005a",
        "on-tertiary-container": "#005f51",
        "surface": "#f5f7f9",
        "surface-container-highest": "#d9dde0",
        "on-surface": "#2c2f31",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#006859",
        "outline": "#747779",
        "inverse-on-surface": "#9a9d9f",
        "on-error": "#ffefef",
        "primary-container": "#e67aff",
        "error-container": "#f74b6d",
        "surface-dim": "#d0d5d8",
        "on-background": "#2c2f31",
        "secondary-fixed-dim": "#c6d7e1",
        "on-secondary-fixed-variant": "#4e5e66",
        "on-tertiary": "#c2ffef",
        "surface-container": "#e5e9eb",
        "secondary-fixed": "#d4e5ef",
        "primary-fixed": "#e67aff",
        "tertiary-dim": "#005a4d",
        "primary-fixed-dim": "#d76df1",
        "error-dim": "#a70138",
        "outline-variant": "#abadaf",
        "on-tertiary-fixed-variant": "#006a5a",
        "primary-dim": "#8315a0",
        "surface-tint": "#9128ad",
        "tertiary-fixed-dim": "#5aeed2",
        "inverse-primary": "#e67aff",
        "tertiary-fixed": "#6bfde0",
        "on-tertiary-fixed": "#004a3f",
        "on-secondary-fixed": "#324249",
        "error": "#b41340",
        "secondary-container": "#d4e5ef",
        "surface-container-high": "#dfe3e6",
        "surface-bright": "#f5f7f9",
        "on-primary-fixed-variant": "#56006b",
        "primary": "#9128ad",
        "surface-variant": "#d9dde0",
        "inverse-surface": "#0b0f10",
        "on-surface-variant": "#595c5e",
        "on-secondary": "#e4f5ff",
        "tertiary-container": "#6bfde0",
        "surface-container-low": "#eef1f3",
        "on-error-container": "#510017",
        "background": "#f5f7f9",
        "warning": "#a95a08"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Manrope"],
        label: ["Manrope"]
      },
      boxShadow: {
        'ambient': '0px 12px 32px rgba(44,47,49,0.06)',
      }
    },
  },
  plugins: [],
}